name: "License check"
on:
  - pull_request
  - workflow_dispatch

jobs:
  test:
    name: license check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install feluda
      - run: feluda
